# use "yapm install ." if you're installing this from git repository

name: sinopia_zzc
version: 1.4.3
description: Private npm repository server

author:
  name: Alex Kocharin
  email: alex@kocharin.ru

repository:
  type: git
  url: git://github.com/zuzuchefe/sinopia

main: index.js

bin:
  sinopia: ./bin/sinopia

dependencies:
  express: '>=5.0.0-0 <6.0.0-0'

  # express middlewares
  express-json5: '>=0.1.0 <1.0.0-0'
  body-parser: '>=1.9.2 <2.0.0-0'
  compression: '>=1.2.0 <2.0.0-0'

  commander: '>=2.3.0 <3.0.0-0'
  js-yaml: '>=3.0.1 <4.0.0-0'
  cookies: '>=0.5.0 <1.0.0-0'
  request: '>=2.31.0 <3.0.0-0'
  async: '>=0.9.0 <1.0.0-0'
  es6-shim: '0.21.x'
  semver: '>=2.2.1 <5.0.0-0'
  minimatch: '>=0.2.14 <2.0.0-0'
  bunyan: '>=0.22.1 <2.0.0-0'
  handlebars: '2.x'
  highlight.js: '8.x'
  lunr: '>=0.5.2 <1.0.0-0'
  render-readme: '>=0.2.1'
  jju: '1.x'
  JSONStream: '1.x'

  mkdirp: '>=0.3.5 <1.0.0-0'
  sinopia-htpasswd: '>= 0.4.3'
  http-errors: '>=1.2.0'

  # node 0.10 compatibility, should go away soon
  readable-stream: '~1.1.0'

optionalDependencies:
  # those are native modules that could fail to compile
  # and unavailable on windows
  fs-ext: '>=0.4.1 <1.0.0-0'
  crypt3: '>=0.1.6 <1.0.0-0' # for sinopia-htpasswd

devDependencies:
  #
  # Tools required for testing
  #
  rimraf: '>=2.2.5 <3.0.0-0'
  bluebird: '2 >=2.9'

  mocha: '2 >=2.2.3'

  #
  # Linting tools
  #
  eslint: '1 >=1.1.0'

  # for debugging memory leaks, it'll be require()'d if
  # installed, but I don't want it to be installed everytime
  #heapdump: '*'

  #
  # Tools required to build static files
  #
  browserify: '7.x'
  browserify-handlebars: '1.x'
  grunt: '>=0.4.4 <1.0.0-0'
  grunt-cli: '*'
  grunt-browserify: '>=2.0.8 <3.0.0-0'
  grunt-contrib-less: '>=0.11.0 <1.0.0-0'
  grunt-contrib-watch: '>=0.6.1 <1.0.0-0'

  # for building static/main.js,
  # not required in runtime
  unopinionate: '>=0.0.4 <1.0.0-0'
  onclick: '>=0.1.0 <1.0.0-0'
  transition-complete: '>=0.0.2 <1.0.0-0'

keywords:
  - private
  - package
  - repository
  - registry
  - modules
  - proxy
  - server

scripts:
  test: eslint . && mocha ./test/functional ./test/unit
  test-travis: eslint . && mocha -R spec ./test/functional ./test/unit
  test-only: mocha ./test/functional ./test/unit
  lint: eslint .
  prepublish: js-yaml package.yaml > package.json
  clean-shrinkwrap: |
    node -e '
      function clean(j) {
        if (!j) return
        for (var k in j) {
          delete j[k].from
          delete j[k].resolved
          if (j[k].dependencies) clean(j[k].dependencies)
        }
      }
      x = JSON.parse(require("fs").readFileSync("./npm-shrinkwrap.json"))
      clean(x.dependencies)
      x = JSON.stringify(x, null, "  ")
      require("fs").writeFileSync("./npm-shrinkwrap.json", x + "\n")
    '

# we depend on streams2 stuff
# it can be replaced with isaacs/readable-stream, ask if you need to use 0.8
engines:
  node: '>=0.10'

preferGlobal: true

publishConfig:
  registry: https://registry.npmjs.org/

license:
  type: WTFPL
  url: http://www.wtfpl.net/txt/copying/
